---
# handlers file for mesos
- name: Restart mesos master
  service: name=mesos-master state=restarted
  sudo: yes

- name: Restart mesos slave
  service: name=mesos-slave state=restarted
  sudo: yes