---
- name: create cluster user on all hosts
# TODO: replace with using of previously generated sshkey
  user: name={{ clusteruser }} generate_ssh_key=yes state=present
  # ignore 'permission denied' errors when user is already shared across NFS
  ignore_errors: yes
  tags:
    - install

- name: put SSH key to host
  copy: src={{ sshkeys_path }}/{{ item }} dest={{ clusteruser_home }}/.ssh/{{ item }}
  with_items:
    - id_rsa
    - id_rsa.pub
    - authorized_keys
  tags:
    - install

## not a good way. that's needed to be able to stop mesos cluster which is running under root (despite of it started by clusteruser).
#- name: put SSH key to host
#  copy: src={{ sshkeys_path }}/{{ item }} dest=root/.ssh/{{ item }}
#  with_items:
#    - id_rsa
#    - id_rsa.pub
#    - authorized_keys
#  tags:
#    - install

- name: disable strict host checking for cluster user
  copy: src=sshconfig dest=/home/{{ clusteruser }}/.ssh/config
  tags:
    - install

- name: add cluster user to sudoers
  lineinfile: "dest=/etc/sudoers
  insertafter=EOF
  line='{{ clusteruser }} ALL=(ALL) NOPASSWD: ALL'
  regexp='{{ clusteruser }} ALL=(ALL) NOPASSWD: ALL'
  state=present"
  tags:
    - install

- name: tune limits to count of open files (soft)
  lineinfile: "dest=/etc/security/limits.conf
  insertafter=EOF
  line='* hard nofile 20000'
  regexp='\\* hard nofile 20000'
  state=present"
  tags:
    - install

- name: tune limits to count of open files (hard)
  lineinfile: "dest=/etc/security/limits.conf
  insertafter=EOF
  line='* soft nofile 20000'
  regexp='\\* soft nofile 20000'
  state=present"
  tags:
    - install