- name: Install JNA
  apt: name=libjna-java state=present
  tags:
    - install

- name: Add Datastax repository key
  apt_key: url=http://debian.datastax.com/debian/repo_key state=present
  tags:
    - install

- name: Add Datastax repository
  apt_repository: repo='deb http://debian.datastax.com/community stable main' state=present update_cache=yes
  tags:
    - install

- name: Install Cassandra
  apt: name={{ item }} state=present
  with_items:
#    - dsc20
    - cassandra
#    - opscenter
#    - datastax-agent
  tags:
    - install

# Basic configuration for Cassandra
- name: disable swap
  shell: swapoff --all
  tags:
    - configure

- name: set virtual memory
  shell: >
    echo "vm.max_map_count = 131072" >> /etc/sysctl.conf
    sysctl -p
  tags:
    - configure

#- name: set up cassandra-env.sh
#  template: src=cassandra-env.sh.j2 dest=/etc/cassandra/cassandra-env.sh
#  tags:
#    - configure

- name: set up cassandra.yaml
  template: src=cassandra.yaml.j2 dest=/etc/cassandra/cassandra.yaml
  tags:
    - configure

#- name: set up datastax agents
#  template: src=address.yaml.j2 dest=/var/lib/datastax-agent/conf/address.yaml
#
- name: make sure cassandra is started
  service: name=cassandra state=restarted
  tags:
    - configure
#
#- name: start datastax-agent
#  service: name=datastax-agent state=restarted
#  tags:
#    - configure


