---
# Run with   $ ansible-playbook site.yml --skip-tags: 'stop' See: site.yml

- name: create non-root clusteruser user
  hosts: all
  sudo:	yes
  roles:
    - clusteruser_common
  any_errors_fatal: yes


- name: deploy and configure the mesos masters
  hosts: mesos_masters
  sudo: True
  roles:
    - { role: mesos, mesos_install_mode: "master", tags: ["mesos-master"] }
  any_errors_fatal: yes


- name: deploy and configure the mesos slaves
  hosts: mesos_slaves
  sudo: True
  roles:
    - { role: mesos, mesos_install_mode: "slave", tags: ["mesos-slave"] }
  any_errors_fatal: yes
