---
- include_vars: roles/spark_standalone/vars/main.yml
  tags:
    - configure

- include_vars: roles/hadoop_common/vars/main.yml
  tags:
    - configure

- include_vars: roles/mesos/vars/main.yml
  tags:
    - configure

- name: Create /tmp on HDFS
  shell: su - {{ hdfsuser }} -c "hadoop fs -mkdir /tmp"
  # ignore errors if file exists
  sudo: yes
  ignore_errors: true
  tags:
    - configure 

- name: Upload Spark package to HDFS
  shell: su - {{ hdfsuser }} -c "hadoop fs -put /tmp/spark-{{ spark_version }}.tgz /tmp"
  # ignore errors if file exists
  sudo: yes
  ignore_errors: true
  tags:
    - configure 

- name: Configure Spark to use Mesos
  template: src=conf/spark-env.sh.j2 dest=/opt/spark/conf/spark-env.sh
  sudo: yes
  tags:
    - configure 

- name: increase default spark.executor.memory parameter
  template: src=conf/spark-defaults.conf.j2 dest={{ spark_root }}/conf/spark-defaults.conf
  sudo: yes
  tags:
    - configure 
